https://jalammar.github.io/illustrated-bert/
https://www.youtube.com/watch?v=7kLi8u2dJz0

for sentiment analysis: https://nlp.stanford.edu/sentiment/index.html

In [1]:
import tensorflow as tf

2025-04-19 15:10:43.758245: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-19 15:10:43.982269: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-19 15:10:44.171365: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1745068244.350296   17768 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1745068244.393654   17768 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1745068244.753028   17768 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linkin

In [4]:
import tensorflow_text as text
import tensorflow_hub as hub

In [6]:
preprocess_url = "https://kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-preprocess/3"
encoder_url = "https://www.kaggle.com/models/tensorflow/bert/TensorFlow2/bert-en-uncased-l-12-h-768-a-12/2"

In [7]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

2025-04-19 15:14:08.785192: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error


In [9]:
text_test = ['nice movie indeed',"I love python programming"]
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [13]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [14]:
text_preprocessed['input_word_ids']

# CLS nice movie indeed SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [16]:
bert_model = hub.KerasLayer(encoder_url)

bert_results = bert_model(text_preprocessed)
bert_results.keys()

2025-04-19 15:20:45.396922: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 93763584 exceeds 10% of free system memory.


dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [17]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[ 0.31700462, -0.00897197,  0.9470522 , ..., -0.7634877 ,
         0.16718099,  0.9982938 ],
       [ 0.39914107, -0.14203481,  0.90585756, ..., -0.7831946 ,
         0.1745231 ,  0.9984515 ]], dtype=float32)>

In [ ]:
len(bert_results['pooled_output'])

2

: 

In [18]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-0.8017657 ,  0.32361305,  0.06374495, ...,  0.16129719,
         -0.40045086, -0.5926615 ],
        [ 0.12236691, -0.02574359,  0.33795944, ...,  0.42200807,
         -0.00308708, -0.01367661],
        [-0.22754851,  0.13265494,  0.12623447, ..., -0.1324513 ,
         -0.29856193, -0.6510194 ],
        ...,
        [-0.09692165,  0.29766482,  0.28932065, ..., -0.09318294,
         -0.08340836,  0.21456799],
        [-0.22733027,  0.42583948,  0.0860447 , ...,  0.00257951,
          0.02146187,  0.25903422],
        [-0.22111079,  0.7789582 , -0.07339046, ...,  0.01744254,
         -0.07840022, -0.229179  ]],

       [[ 0.05904214, -0.2120412 , -0.13617806, ...,  0.43750256,
          0.50269586, -0.35996303],
        [ 0.67072994,  0.1404895 , -0.09224141, ...,  0.42108846,
          0.4111905 , -0.55841184],
        [ 0.17798139, -0.4903903 , -0.3866708 , ...,  0.12570105,
         -0.2774936 , -0.15996669],
        ...,

In [19]:
len(bert_results['sequence_output'])

2